### ISSUE TITLE
[Question] Encryption key type.

### ISSUE THREAD

**Issue by Rietty** [andrew1421lee/ROFL-Player#13]
Hi, do you have any information regarding the encryption key? Like what parts of the file are encrypted? Is it everything starting after the data/payload offset, or is it only the chunk/keyframe information? Do you know what type of encryption format it is? I was guessing at AES or BigCrypt but I'm not sure? Is it possible to even decrypt the data?

**Comment by fraxiinus** [comment]
There isn't a whole lot of information out about the rest of the information in the replay files. No one really knows what encryption they use, but I think I saw someone claim it was Blowfish. Additionally, the actual packet data in the replay file is obfuscated in the same way live packet data is obfuscated in live games. The obfuscation "key" changes each patch which is what makes old replays incompatible.
