### ISSUE TITLE
I don't see a ROFLPlayer.exe

### ISSUE THREAD

**Issue by vluu2** [andrew1421lee/ROFL-Player#15]
When I unzipped the ROFL-Player-master folder, there is no ROFLPlayer.exe file that you are saying is there... The only thing I see is ROFLPlayer.sln, README, and then the folders containing ROFLPlayer and Rofl.Parser.......... Am I missing something?

**Comment by fraxiinus** [comment]
You downloaded the source code, not the release. Download the release here:

https://github.com/andrew1421lee/ROFL-Player/releases
