### ISSUE TITLE
Bugsplat

### ISSUE THREAD

**Issue by gschurck** [andrew1421lee/ROFL-Player#16]
It's actually impossible to open .rofl files with the software on patch 9.4. When I try to open there is always a Bugsplat.

**Comment by fraxiinus** [comment]
I can't reproduce the bugsplat, it works fine for me on 9.4.
Please check your executable path in ROFL Player settings. It should be something like:

[...] \RADS\solutions\lol_game_client_sln\releases\0.0.2.3\deploy\League of Legends.exe

**Comment by fraxiinus** [comment]
Could not reproduce, no followup
