### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by PentaAsian** [andrew1421lee/ROFL-Player#21]
![roflPlayer1](https://user-images.githubusercontent.com/42952256/58512728-80785700-8139-11e9-857e-b93118ce7274.PNG)

I keep getting this every time I open up the app. If I hit continue, it loads the ROFLPlayer app forever until I hit the x to close the window and hitting quit on this doesn't load it.

**Comment by fraxiinus** [comment]
You have to run RoflPlayer in the same folder as the "lib" folder. Also, please follow these instructions to get around the new Riot Patcher. https://github.com/leeanchu/ROFL-Player/issues/17#issuecomment-478376672
