### ISSUE TITLE
replay errer

### ISSUE THREAD

**Issue by tardis7732** [andrew1421lee/ROFL-Player#23]
Other features work perfectly.
but When I press play button, the following message pops up and it is impossible to play.
Failed to play replay: System.AggregateException One or more errors occurred.

**Comment by fraxiinus** [comment]
Is there any other information in the error? Maybe post a screenshot?

**Comment by tardis7732** [comment]
The states of cpu, gpu, and ram are all in the normal range.
1) The reason I found it on the git hub is that Ziggs error occurred when dragging rofl to C: \ Program Files (x86) \ League of Legends \ Game \ League of Legends.exe.
2) I downloaded the ROFL-Player located C:\Users\SSM\Desktop\ROFLPlayer (1). I opened the exe file and set it like this.
3) The replay files are located at C: \ Users \ SSM \ Documents \ League of Legends \ Replays.
4) Double-click the rofl file and it works like this.
5) Now, when you press play, Ziggs error occurs. Previously (System.AggregateException One or more errors occurred), but not now.
6) It is the same as the rofl file version and league of legends version.
7) I wonder if your program is a problem or my other setting is a problem.

![about](https://user-images.githubusercontent.com/52117406/59983899-5a25d880-965f-11e9-94a9-a002999e2846.jpg)
![detail_general](https://user-images.githubusercontent.com/52117406/59983900-5abe6f00-965f-11e9-80d3-6810729574e7.jpg)
![detail_player stats](https://user-images.githubusercontent.com/52117406/59983901-5abe6f00-965f-11e9-9a95-4365134c9d18.jpg)
![excutable](https://user-images.githubusercontent.com/52117406/59983902-5abe6f00-965f-11e9-8a0a-0260594aa554.jpg)
![general](https://user-images.githubusercontent.com/52117406/59983903-5abe6f00-965f-11e9-9a5b-5078260ad482.jpg)

**Comment by fraxiinus** [comment]
Oh I think I understand what is going on! I haven't tested ROFLPlayer on different Windows languages. Can you post the content of Default.json in the 'execs' folder where ROFLPlayer is?

**Comment by fraxiinus** [comment]
Try using the new release, it should give more helpful error messages. Let me know what it says now.

https://github.com/leeanchu/ROFL-Player/releases/tag/0.9c-beta

**Comment by fraxiinus** [comment]
The solution for ROFLPlayer is to use the English version of League. The redesign of ROFLPlayer (https://github.com/leeanchu/ReplayBook) will solve this issue.
