### ISSUE TITLE
Making a ROFL HUB

### ISSUE THREAD

**Issue by ghost** [andrew1421lee/ROFL-Player#25]
Hey ! It's me again ^^
Here's the proposition I wanted to make :  

My idea behind this is not to make a small app that can open ROFL files individually. It feels like wasted potential and it's quite frustrating when I want to check many replays to find the right one or to compare them.

So I propose to make it a strong match history analyzing tool while highlithing the ease of use of the software (no need for a million click or for checking champion by champion). Here is how it works :

**Basic functionalities :**
When you first open it, it will take some time to scan the whole default replay folder (or any folder the user wants) and then give you a list of all the replays so you can check them in a drop down menu and easily switch between them instead of opening them one by one in a folder (which takes time and it's not very practical).
The app should also have an option to sort/filter them by name, date, patch, champion (since users can add their summoner name in the current app, it should be able to check the champion he's playing), wins and losses.
An option to rename them would also be welcomed.
It should also provide the general and the stat tabs like the client's match history since all those data are available in the ROFL file (the current app can already do that, it's just better to use a bigger window and show all the champs in one go like the client's match history instead of having to choose them one by one).

**Advances functionalities :**

Maybe you could even add the graphs (like the damage one or gold evolution during the game) or other things it's lacking to make it an attractive small analytical tool.
Example : Showing the stats of the 2 midlaners side by side to easily compare them or showing the gold that a gold graph of only one player to see how he contributed during the whole game (maybe he forgot about farm after the laning phase)

It would look like this : 
![Screenshot_2](https://user-images.githubusercontent.com/50350165/61698241-06c7a880-ad39-11e9-9288-3ce7ac423ccb.png)

This is gonna be a lot of work, but I'm sure it's doable and worth it. I personally believe that you should make at least the basic functionalities come true since they are core to your ROFL player app. The other ones can come later (or never).

What do you think of those suggestions?

**Comment by fraxiinus** [comment]
Hi, I appreciate all the effort you put into this suggestion!
I have been planning to do something similar when I first started ROFLPlayer. I first wanted to somehow integrate into Windows Explorer, but I realize now that a separate app would be much simpler. I planned on implementing something like this when I got around replacing the old WinForms UI ROFLPlayer uses with WPF. 
I'm currently working to untangle all the important logic from the old UI and into their own libraries. Once I get that done replacing the UI should be a much easier job. When I start working on the UI, I will update this thread with my progress.

**Comment by fraxiinus** [comment]
I opened a new project https://github.com/leeanchu/ROFL-Player/projects/2 that I'll use to list progress. Keep in mind it may be months before I'm able to start work.

**Comment by ghost** [comment]
That's great news !
Yeah I know it will take time. And glad you're planning to do it.
Good luck^^

**Comment by fraxiinus** [comment]
The redesign project has it's own repository at https://github.com/leeanchu/ReplayBook
