### ISSUE TITLE
Open Replay - BugSplat

### ISSUE THREAD

**Issue by herons2** [andrew1421lee/ROFL-Player#27]
Hi!
Whenever I try to play replay with the ROFL-Player, my game crashe, ''BUGSPLAT''
I play server in Brazil

**Comment by fraxiinus** [comment]
Hello! 
Can you post the contents of the files in the "execs" folder? You can find it in the same folder as ROFLPlayer.exe

**Comment by herons2** [comment]
Hi!
Yes, 
''{"Name":"Lol Videos","TargetPath":"E:\\TESTE - RITO\\League of Legends\\Game\\League of Legends.exe","StartFolder":"E:\\TESTE - RITO\\League of Legends\\Game","PatchVersion":"9.14.282.7724","AllowUpdates":false,"IsDefault":true,"ModifiedDate":"2019-07-22T21:53:03.9181393-03:00"}''

**Comment by fraxiinus** [comment]
The the file seem fine. Can you attach a screenshot of the files in "E:\TESTE - RITO\League of Legends"?

**Comment by herons2** [comment]
Sure,
https://imgur.com/a/Y32zFs9
i found a folder in lol called LOG after replay crash
''000000.000| ALWAYS| Logging started at 2019-07-29T22:01:07.951
000000.013| ALWAYS| Begin command line toggles...
000000.013| ALWAYS| End command line toggles.
000000.020| ALWAYS|   CFG| Crashpad Disabled
000000.030| ALWAYS| Command line: C:\Users\Heimer\Documents\League of Legends\Replays\BR1-1708434200.rofl
000000.030| ALWAYS| Parent process: C:\Windows\explorer.exe
000000.040|   OKAY| Riot::RADS::Reader::RadsMain::Initialize: RADS library initializing with specified working directory "C:\Riot Games\League of Legends\Game".
000000.040|   OKAY| Riot::RADS::Reader::RuntimeEnvironment::Create: Creating RADS runtime environment: RADS root directory = "C:/Riot Games/League of Legends/Game"
000000.041|   WARN| Riot::RADS::Reader::RuntimeEnvironment::GetProjectTypeNameAndVersion: Did not find keywords "projects" or "solutions" in path C:/Riot Games/League of Legends/Game
000000.041|  ERROR| Riot::RADS::Reader::RuntimeEnvironment::Create: RADS runtime environment creation failed because it was unable to get the project information.
000000.041|  ERROR| Riot::RADS::Reader::RadsMain::Initialize: RADS library initialization failed to create the runtime environment.
000000.041|  ERROR| Failed to initialize Rads library.
000000.043| ALWAYS| Riot::RADS::Reader::SignalSoftRepair: Wrote soft repair file to C:/Riot Games/League of Legends/SOFT_REPAIR. This will cause the patcher to repair your installation.
000000.082| ALWAYS| WadFile mount: DATA/FINAL/Global.wad.client
000000.087| ALWAYS| WadFile mount: DATA/FINAL/Scripts.wad.client
000000.087| ALWAYS| WadFile mount: DATA/FINAL/UI/ui.wad.client
000000.088| ALWAYS| WadFile mount: DATA/FINAL/Shaders/Shaders.wad.client
000000.093| ALWAYS| WadFile mount: DATA/FINAL/DATA.wad.client
000000.140| ALWAYS| Riot::RADS::Reader::SignalSoftRepair: Wrote soft repair file to C:/Riot Games/League of Legends/SOFT_REPAIR. This will cause the patcher to repair your installation.
000000.143|  ERROR| Assertion failed!


Expression: ALE-18967991

Description: FATAL ERROR - Installation is corrupt. WadFile mount failed.
 - WadFile: DATA/FINAL/Localized/Global.en_us.wad.client
 - Problem: Missing
000000.418| ALWAYS|  CRSH| BugSplat: ''

**Comment by fraxiinus** [comment]
Try using the latest released of ROFLPlayer, though this problem sounds more like a problem with your League of Legends install

**Comment by herons2** [comment]
Hello
I found the problem, 
''Global.en_us.wad.client'', after install NA, and download this file replays work perfect
this ''bug'', not caused by your soft, but by the regions of lol
Thx for suport. <3

**Comment by heypedro** [comment]
@herons2 você pode me ajudar? estou tendo o mesmo problema, sendo que já alterei o idioma para inglês e não resolveu.
