### ISSUE TITLE
Doesn't seem to work for LoL version 9.21

### ISSUE THREAD

**Issue by lare96** [andrew1421lee/ROFL-Player#34]
Downloaded a mirror of 9.21 from majorgeeks. The main directory looks like this

![](https://i.imgur.com/v2RihYO.png)

I try to select "LeagueClient" and it gives me this error

![](https://i.imgur.com/h58STPD.png)

The installation does not include those folders (as you can see in the 1st pic). I'm on the latest version of ROFL-Player (1.1). What would be the best course of action here? Any help is appreciated.

**Comment by fraxiinus** [comment]
The installation you got is incomplete. It seems to only contain the league client and not the game itself. There should be a RADS or GAME folder
