### ISSUE TITLE
Bugsplat whenever clicking play

### ISSUE THREAD

**Issue by tekn02** [andrew1421lee/ROFL-Player#35]
That's it. Whenever I try to play a replay, I get a bugsplat error. I've tried with replays that are from the same day that I'm trying to open them but I'm still getting the same error.

**Comment by tekn02** [comment]
Oh, ok. I have just seen Issue #27 but I don't understand what he did to fix it lol.

**Comment by fraxiinus** [comment]
Bugsplat means theres something wrong with the game. Either you are using a non-english version of league of legends or there is something wrong with the installation.

You can post your `\ROFLPlayer\data\executables.json` file here and I can take a look.

**Comment by tekn02** [comment]
I was using a non-english version. I changed it to english and now it works! By the way, I couldn't open ANY replay even without ROFLPlayer, so you fixed even that! Thank you very much.

**Comment by fraxiinus** [comment]
glad to help :)
