### ISSUE TITLE
You Forgot to Add ;

### ISSUE THREAD

**Issue by sweetriverfish** [andrew1421lee/ROFL-Player#36]
ROFL-Player-master\Rofl.Reader\ReplayReader.cs is missing ; at line 90

**Comment by fraxiinus** [comment]
Whoops looks like a previous pull request wasn't properly checked.
However, I am no longer actively maintaining ROFLPlayer as I continue work on ReplayBook.

If you'd like to contribute you can submit a pull request to fix it. Otherwise I can do it. Eventually.
