### ISSUE TITLE
How do i lunch the program ? 

### ISSUE THREAD

**Issue by hakushakusama** [andrew1421lee/ROFL-Player#4]
i don't know what file to open since there is no  exe   or anything app that windows could open

**Comment by fraxiinus** [comment]
You can get the executable in the Releases page. https://github.com/andrew1421lee/ROFL-Player/releases

**Comment by hakushakusama** [comment]
ty a lot ^^


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
