### ISSUE TITLE
Scrub through game timeline without leagueoflegends.exe

### ISSUE THREAD

**Issue by ciriousjoker** [andrew1421lee/ROFL-Player#40]
I'm looking for a way to get champion positions, cooldowns, objective/camp status, minion positions and health for any given point in time during the match. Is there a way to do that? Maybe it's not possible with this tool, but can this be achieved at all or is the info obfuscated and shuffled with each patch?

**Comment by fraxiinus** [comment]
There is also no way to view information about the match at a particular time. The only way is to use Riot's timeline api, which only has a a snapshot every few moments.

https://developer.riotgames.com/apis#match-v4

**Comment by ciriousjoker** [comment]
Some of the data is already available via the match api (thanks!), but if I want the full details, I'll probably have to resort to replaying the match and reading the data from leagueoflegends.exe's memory directly... Maybe I abandon this idea, maybe I continue it, who knows..
