### ISSUE TITLE
Add Executables table not fully displayed 

### ISSUE THREAD

**Issue by Svorpal** [andrew1421lee/ROFL-Player#43]
Hi,
Thank you for your awesome work!
When I tried to run the ROFLPLAYER.exe, it says "ROFLPlayer was not able to find League of Legends. Please add it now."
Then the window of "Add Executable..." popped up, but I could only see the upper half of it.
The last sentence displayed was "Last Modified: xxxx " and there were not any save or cancel buttons. 
As a result, I could not proceed to the next step.
It would be great if you could help!

**Comment by fraxiinus** [comment]
Hello, this is a known issue with ROFLPlayer, I'm not exactly sure why it is happening. For now, I suggest you use ReplayBook instead and see if it can fulfill your use case, to get it just join my Discord server and ask for the download. https://discord.com/invite/c33Rc5J.

Note: Could you tell me the following information, it may help me pinpoint why this is happening.
* Screen resolution (1920x1080?)
* Windows Version (Windows 10/7/etc). If windows 10, please include build number.
* Windows Language (English, Chinese, etc)

**Comment by Svorpal** [comment]
Thanks!
Screen resolution : 1920x1080
Windows Version: win10 1909
Windows Language: English, Chinese (both didn't work)
