### ISSUE TITLE
Error Upon opening file

### ISSUE THREAD

**Issue by ughstudios** [andrew1421lee/ROFL-Player#46]
![image](https://user-images.githubusercontent.com/1284431/119505619-223bda00-bd3b-11eb-84f5-4e7c240bc93e.png)

I get this when I try to open a ROFL file

**Comment by fraxiinus** [comment]
Try using this program instead https://github.com/fraxiinus/ReplayBook

If that doesn't work, there's a good chance that replay file is corrupted.
