### ISSUE TITLE
Do Change "WARD_PLACED" Not "WARDS_PLACED"

### ISSUE THREAD

**Issue by 1Sam** [andrew1421lee/ROFL-Player#47]
https://github.com/fraxiinus/ROFL-Player/blob/90bdcdf0d256f992b3895d5c734d60e501468ba6/Rofl.Reader/Utilities/GameDetailsInferrer.cs#L39

**Comment by 1Sam** [comment]
What a exelent nice good effort it is. You are so amazing~
I wanted to get metadata of custom games. Sometimes riot api support custom game with matchId. But now you show me the other way to get the information of custom games.
Wow~

**Comment by fraxiinus** [comment]
Thank you for your kind words!
ROFL-Player is not being updated anymore, so this issue was fixed in [ReplayBook](https://github.com/fraxiinus/ReplayBook).
Please check it out
